### ISSUE TITLE
Feedback on first few steps of hw2

### ISSUE THREAD

**Issue by troyshu** [cuny-sps-msda-data622-2017fall/data622hw2#2]
Putting myself in the shoes of a student, I wasn't too sure about how to do the requirements.txt part, because sklearn, pandas, etc. are all in the docker container. So do I write the pipeline scripts (e.g. pull_data.py) while inside the docker container (e.g. after running `docker exec <container_id> bash`), because those scripts will need sklearn, pandas, etc.? Or do I write it outside of docker, locally, perhaps in a virtual environment (and install sklearn, pandas, etc. in there too)?

It looks like the dataquestio python3 docker image uses requests==2.2.1, which causes a Google Cloud error of some sort when trying to download the CSVs from Kaggle (see discussion in #homework2 channel, code at https://gist.github.com/troyshu/ce36e8785d8dcd7803805b00f1f3516d). When using requests==2.18.4, which according to my testing is the default requests version installed when using python 3 or python 2, the CSVs download successfully.

So perhaps we should clarify that this homework is to be done outside of the docker (clearing up the requirements.txt part, and enabling requests to download the CSVs successfully)?

**Comment by sunwsusan** [comment]
Thank you for the feedback!  I addressed some of this in the Slack channel, but will summarize here, since that conversation meandered quite a bit.  Let me know what you think:

1. Dataquest's python3 docker image requires a lot of package updates.  I was aware of that, but assumed that students would be able to see this and comfortably infer they will need to do a pip install --upgrade.  I see now that I shouldn't have made that assumption, but hopefully this has been addressed by my helping Christina debug her hw on the slack channel.  

2. I toyed with the idea of asking the students to just upload their docker image for grading, but I also wanted them to get the experience of using github repo as a code repo, which means getting used to updating the ReadMe documentation and understanding how to instruct users to download dependencies.  That was the reasoning behind insisting they create requirements.txt even though they are already ssh-ed into a Docker image.   Yes, technically students can still do this outside of Docker, in a virtualenv, but that will generate more work later on, where, in hw3, I'm planning to ask them to upload their docker image to Kubernetes on Google Compute Engine.  Since hw 3 isn't assigned yet, I'm very open to suggestions and/or comments on how this can fail spectacularly - any insights?

**Comment by troyshu** [comment]
1. Ok yep, hopefully the students will see the conversation in the hw2 slack / know to upgrade the modules in the docker image.

2. Uploading their docker image to kubernetes for the hw3 sounds like good practice for them. And creating a requirements.txt while already ssh-ed into their container makes sense. I was just a little confused by the sentence for requirements.txt "This file documents all dependencies needed *on top* of the existing packages in the Docker Dataquest image", because `pip freeze` will list all packages, including the existing ones already installed in the docker image (which is perhaps what should be in requirements.txt: all the required packages for the repo).

Anyways, feel free to close, maybe I'm just easily confused :)

**Comment by sunwsusan** [comment]
1. Good point.  I'll go over this again during lecture 3.

2. Also good point.  There is a lot of confusion over the requirements.txt part.  I will go over this during lecture 3 one more time, both the practical steps, and also conceptually, what is going on.  Still looking for some good tutorials/resources for Kubernetes 101.  There seems to be a lack of good interactive codelabs on this matter.  Any recommendations, let me know.

Thank you for the feedback!
